<?php
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Url;

/**
 * Implements hook_theme().
 */
function login_user_theme($existing, $type, $theme, $path) {
  return [
    'login_user_template' => [
      'variables' => [
        'user_id' => '',
        'user_img' => '',
        'user_name' => '',
        'user_email' => '',
        'site_path' => ''
      ],
    ],
  ];
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function login_user_form_user_login_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  // Alter login form and add own custom submit handler.
  $form['#submit'][] = '_login_user_login_form_submit';
}

/**
 * Custom submit handler for login form.
 */
function _login_user_login_form_submit($form, FormStateInterface $form_state) {
  $current_url = Url::fromRoute('<current>');
  $path = $current_url->getRouteName();
  $form_state->setRedirect($path);
}
